FROM nvidia/cuda:11.6.1-cudnn8-devel-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y --fix-missing

RUN apt-get update && \
    apt-get install -y --allow-unauthenticated \
    wget \
    git \
    unzip \
    curl \
    libssl-dev \
    libcurl4-openssl-dev \
    zlib1g-dev \
    python3 \
    python3-dev \
    python3-pip \
    libopenmpi-dev \
    libboost-serialization-dev \
    && apt-get clean && \
    ln -sf python3 /usr/bin/python && \
    ln -sf pip3 /usr/bin/pip

RUN pip install \
    astor==0.8.1 \
    numpy==1.16.6 \
    protobuf==3.17.3 \
    mpi4py==3.1.3 && \
    pip install --no-deps \
    keras-preprocessing==1.0.5


RUN apt remove --purge cmake -y && wget http://www.cmake.org/files/v3.21/cmake-3.21.1.tar.gz && \
    tar xf cmake-3.21.1.tar.gz && cd cmake-3.21.1 && ./configure && make -j12 && make install

RUN wget https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh \
    && chmod +x bazel-0.26.1-installer-linux-x86_64.sh \
    && ./bazel-0.26.1-installer-linux-x86_64.sh